### ISSUE TITLE
Historical feasibility on new feasibility maps

### ISSUE THREAD

**Issue by Vcomea** [bcgov/CCISS_Review#39]
There are some major differences in the historical feasibility of species in the new mapping (July 31, 2024). Newer mapping shows lower historical feasibility, which doesn't match up with what is on the ByBEC app. 

      This is evident for Amabilis fir, subalpine fir, trembling aspen and western redcedar. 

Compare the old vs new 2-panel maps here: 
https://bcgov-my.sharepoint.com/:f:/r/personal/will_mackenzie_gov_bc_ca/Documents/CCISSv12/[FeasibilityMaps](https://bcgov-my.sharepoint.com/:f:/r/personal/will_mackenzie_gov_bc_ca/Documents/CCISSv12/FeasibilityMaps?csf=1&web=1&e=X2PT0b)?csf=1&web=1&e=X2PT0b
![image](https://github.com/user-attachments/assets/abd51ef7-0cf2-4017-9d92-e1ce674b6082)
![image](https://github.com/user-attachments/assets/400cd3a2-c210-4fb0-b703-331ded16fa62)

![image](https://github.com/user-attachments/assets/889048a1-80e0-4e13-ab1e-ab9c942b953d)
![image](https://github.com/user-attachments/assets/00ba3780-801a-4c89-aa87-ed2cf43b52ac)

**Comment by cmahony** [comment]
fixed. there was a bad duplicated line of code.

 ![Image](https://github.com/user-attachments/assets/175290a2-2c22-4a6f-920c-31cbf87342ef)
